### ISSUE TITLE
--period-begin does not work

### ISSUE THREAD

**Issue by mniehren** [bkram/zarafa-scan-attachments#2]
Hi,

i played around with your script to scan the kopano-user mails.
As i don't want to scan all mails again and again it tried to use the
--period-begin
option. But it does not make any differenced. It show's me the same
mail's as without the option

 /data/kopano-scan-attachments.py -u michael --period-begin 2018-11-08

**Comment by bkram** [comment]
The period functionality comes from and is handled by the python-kopano module.
Maybe you could try to add an end date as well to see if that helps.

**Comment by mniehren** [comment]
does also not work, sorry. I will take a look into the code of the python-kopano module ...

thanks,
  Michael
